controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    # 控制器列表
    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  # 标准名称
    fishbot_effort_controller:
      type: effort_controllers/JointGroupEffortController  # 标准名称
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

fishbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.20  # 轮子间距
    wheel_radius: 0.032     # 轮子半径

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0      # 发布速率
    odom_frame_id: odom     # 里程计帧ID
    base_frame_id: base_footprint  # 基座帧ID
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false